#!/bin/bash -f
# Vivado (TM) v2015.3 (64-bit)
#
# Filename    : block_diagram.sh
# Simulator   : Synopsys Verilog Compiler Simulator
# Description : Simulation script for compiling, elaborating and verifying the project source files.
#               The script will automatically create the design libraries sub-directories in the run
#               directory, add the library logical mappings in the simulator setup file, create default
#               'do' file, copy glbl.v into the run directory for verilog sources in the design (if any),
#               execute compilation, elaboration and simulation steps.
#
# Generated by Vivado on Sat Dec 05 22:35:03 EST 2015
# IP Build 1367837 on Mon Sep 28 08:56:14 MDT 2015 
#
# usage: block_diagram.sh [-help]
# usage: block_diagram.sh [-lib_map_path]
# usage: block_diagram.sh [-noclean_files]
# usage: block_diagram.sh [-reset_run]
#
# Prerequisite:- To compile and run simulation, you must compile the Xilinx simulation libraries using the
# 'compile_simlib' TCL command. For more information about this command, run 'compile_simlib -help' in the
# Vivado Tcl Shell. Once the libraries have been compiled successfully, specify the -lib_map_path switch
# that points to these libraries and rerun export_simulation. For more information about this switch please
# type 'export_simulation -help' in the Tcl shell.
#
# You can also point to the simulation libraries by either replacing the <SPECIFY_COMPILED_LIB_PATH> in this
# script with the compiled library directory path or specify this path with the '-lib_map_path' switch when
# executing this script. Please type 'block_diagram.sh -help' for more information.
#
# Additional references - 'Xilinx Vivado Design Suite User Guide:Logic simulation (UG900)'
#
# ********************************************************************************************************

# Script info
echo -e "block_diagram.sh - Script generated by export_simulation (Vivado v2015.3 (64-bit)-id)\n"

# Script usage
usage()
{
  msg="Usage: block_diagram.sh [-help]\n\
Usage: block_diagram.sh [-lib_map_path]\n\
Usage: block_diagram.sh [-reset_run]\n\
Usage: block_diagram.sh [-noclean_files]\n\n\
[-help] -- Print help information for this script\n\n\
[-lib_map_path <path>] -- Compiled simulation library directory path. The simulation library is compiled\n\
using the compile_simlib tcl command. Please see 'compile_simlib -help' for more information.\n\n\
[-reset_run] -- Recreate simulator setup files and library mappings for a clean run. The generated files\n\
from the previous run will be removed. If you don't want to remove the simulator generated files, use the\n\
-noclean_files switch.\n\n\
[-noclean_files] -- Reset previous run, but do not remove simulator generated files from the previous run.\n\n"
  echo -e $msg
  exit 1
}

if [[ ($# == 1 ) && ($1 != "-lib_map_path" && $1 != "-noclean_files" && $1 != "-reset_run" && $1 != "-help" && $1 != "-h") ]]; then
  echo -e "ERROR: Unknown option specified '$1' (type \"./block_diagram.sh -help\" for more information)\n"
  exit 1
fi

if [[ ($1 == "-help" || $1 == "-h") ]]; then
  usage
fi

# STEP: setup
setup()
{
  case $1 in
    "-lib_map_path" )
      if [[ ($2 == "") ]]; then
        echo -e "ERROR: Simulation library directory path not specified (type \"./block_diagram.sh -help\" for more information)\n"
        exit 1
      fi
      # precompiled simulation library directory path
     create_lib_mappings $2
     copy_glbl_file
    ;;
    "-reset_run" )
      reset_run
      echo -e "INFO: Simulation run files deleted.\n"
      exit 0
    ;;
    "-noclean_files" )
      # do not remove previous data
    ;;
    * )
     create_lib_mappings $2
     copy_glbl_file
  esac

  # Add any setup/initialization commands here:-

  # <user specific commands>

}

# Copy glbl.v file into run directory
copy_glbl_file()
{
  glbl_file="glbl.v"
  src_file="/opt/Xilinx/Vivado/2015.3/data/verilog/src/glbl.v"
  if [[ ! -e $glbl_file ]]; then
    cp $src_file .
  fi
}

# Remove generated data from the previous run and re-create setup files/library mappings
reset_run()
{
  files_to_remove=(ucli.key block_diagram_simv vlogan.log vhdlan.log compile.log elaborate.log simulate.log .vlogansetup.env .vlogansetup.args .vcs_lib_lock scirocco_command.log 64 AN.DB csrc block_diagram_simv.daidir)
  for (( i=0; i<${#files_to_remove[*]}; i++ )); do
    file="${files_to_remove[i]}"
    if [[ -e $file ]]; then
      rm -rf $file
    fi
  done
}

# Main steps
run()
{
  setup $1 $2
  compile
  elaborate
  simulate
}

# Create design library directory paths and define design library mappings in cds.lib
create_lib_mappings()
{
  libs=(xil_defaultlib lib_cdc_v1_0_2 proc_sys_reset_v5_0_8 generic_baseblocks_v2_1_0 axi_infrastructure_v1_1_0 axi_register_slice_v2_1_6 fifo_generator_v13_0_0 axi_data_fifo_v2_1_5 axi_crossbar_v2_1_7 util_reduced_logic_v2_0 util_vector_logic_v2_0 axi_protocol_converter_v2_1_6)
  file="synopsys_sim.setup"
  dir="vcs"

  if [[ -e $file ]]; then
    rm -f $file
  fi

  if [[ -e $dir ]]; then
    rm -rf $dir
  fi

  touch $file
  lib_map_path="<SPECIFY_COMPILED_LIB_PATH>"
  if [[ ($1 != "" && -e $1) ]]; then
    lib_map_path="$1"
  else
    echo -e "ERROR: Compiled simulation library directory path not specified or does not exist (type "./top.sh -help" for more information)\n"
  fi
  incl_ref="OTHERS=$lib_map_path/synopsys_sim.setup"
  echo $incl_ref >> $file

  for (( i=0; i<${#libs[*]}; i++ )); do
    lib="${libs[i]}"
    lib_dir="$dir/$lib"
    if [[ ! -e $lib_dir ]]; then
      mkdir -p $lib_dir
      mapping="$lib : $dir/$lib"
      echo $mapping >> $file
    fi
  done
}


# RUN_STEP: <compile>
compile()
{
  # Directory path for design sources and include directories (if any) wrt this path
  ref_dir="."
  # Command line options
  opts_ver="-full64 -timescale=1ps/1ps"
  opts_vhd="-full64"

  # Compile design files
  vlogan -work xil_defaultlib $opts_ver +v2k +incdir+"$ref_dir/../../../../zynq-memory-ordering.srcs/sources_1/bd/block_diagram/ipshared/xilinx.com/axi_infrastructure_v1_1/hdl/verilog" +incdir+"$ref_dir/../../../../zynq-memory-ordering.srcs/sources_1/bd/block_diagram/ipshared/xilinx.com/processing_system7_bfm_v2_0/hdl" +incdir+"$ref_dir/../../../bd/block_diagram/ip/block_diagram_processing_system7_0_0" +incdir+"$ref_dir/../../../bd/block_diagram/ipshared/xilinx.com/ila_v6_0/hdl/verilog" +incdir+"$ref_dir/../../../bd/block_diagram/ipshared/xilinx.com/ltlib_v1_0/hdl/verilog" +incdir+"$ref_dir/../../../bd/block_diagram/ipshared/xilinx.com/xsdbm_v1_1/hdl/verilog" +incdir+"$ref_dir/../../../bd/block_diagram/ipshared/xilinx.com/xsdbs_v1_0/hdl/verilog" +incdir+"$ref_dir/../../../../zynq-memory-ordering.srcs/sources_1/bd/block_diagram/ip/block_diagram_processing_system7_0_0" +incdir+"$ref_dir/../../../../zynq-memory-ordering.srcs/sources_1/bd/block_diagram/ipshared/user.org/hardware_accelerator_v1_0/drivers/hardware-accelerator_v1_0/src" +incdir+"$ref_dir/../../../../zynq-memory-ordering.srcs/sources_1/bd/block_diagram/ipshared/xilinx.com/axi4_metrics_counter_v1_0/drivers/axi3_metrics_counter_v1_0/src" +incdir+"$ref_dir/../../../../zynq-memory-ordering.srcs/sources_1/bd/block_diagram/ipshared/xilinx.com/ila_v6_0/hdl/verilog" +incdir+"$ref_dir/../../../../zynq-memory-ordering.srcs/sources_1/bd/block_diagram/ipshared/xilinx.com/ltlib_v1_0/hdl/verilog" +incdir+"$ref_dir/../../../../zynq-memory-ordering.srcs/sources_1/bd/block_diagram/ipshared/xilinx.com/xsdbm_v1_1/hdl/verilog" +incdir+"$ref_dir/../../../../zynq-memory-ordering.srcs/sources_1/bd/block_diagram/ipshared/xilinx.com/xsdbs_v1_0/hdl/verilog" +incdir+"$ref_dir/../../../ipstatic/axi_infrastructure_v1_1/hdl/verilog" +incdir+"$ref_dir/../../../ipstatic/processing_system7_bfm_v2_0/hdl" \
    "$ref_dir/./../../../../zynq-memory-ordering.srcs/sources_1/bd/block_diagram/ipshared/xilinx.com/processing_system7_bfm_v2_0/hdl/processing_system7_bfm_v2_0_arb_wr.v" \
    "$ref_dir/./../../../../zynq-memory-ordering.srcs/sources_1/bd/block_diagram/ipshared/xilinx.com/processing_system7_bfm_v2_0/hdl/processing_system7_bfm_v2_0_arb_rd.v" \
    "$ref_dir/./../../../../zynq-memory-ordering.srcs/sources_1/bd/block_diagram/ipshared/xilinx.com/processing_system7_bfm_v2_0/hdl/processing_system7_bfm_v2_0_arb_wr_4.v" \
    "$ref_dir/./../../../../zynq-memory-ordering.srcs/sources_1/bd/block_diagram/ipshared/xilinx.com/processing_system7_bfm_v2_0/hdl/processing_system7_bfm_v2_0_arb_rd_4.v" \
    "$ref_dir/./../../../../zynq-memory-ordering.srcs/sources_1/bd/block_diagram/ipshared/xilinx.com/processing_system7_bfm_v2_0/hdl/processing_system7_bfm_v2_0_arb_hp2_3.v" \
    "$ref_dir/./../../../../zynq-memory-ordering.srcs/sources_1/bd/block_diagram/ipshared/xilinx.com/processing_system7_bfm_v2_0/hdl/processing_system7_bfm_v2_0_arb_hp0_1.v" \
    "$ref_dir/./../../../../zynq-memory-ordering.srcs/sources_1/bd/block_diagram/ipshared/xilinx.com/processing_system7_bfm_v2_0/hdl/processing_system7_bfm_v2_0_ssw_hp.v" \
    "$ref_dir/./../../../../zynq-memory-ordering.srcs/sources_1/bd/block_diagram/ipshared/xilinx.com/processing_system7_bfm_v2_0/hdl/processing_system7_bfm_v2_0_sparse_mem.v" \
    "$ref_dir/./../../../../zynq-memory-ordering.srcs/sources_1/bd/block_diagram/ipshared/xilinx.com/processing_system7_bfm_v2_0/hdl/processing_system7_bfm_v2_0_reg_map.v" \
    "$ref_dir/./../../../../zynq-memory-ordering.srcs/sources_1/bd/block_diagram/ipshared/xilinx.com/processing_system7_bfm_v2_0/hdl/processing_system7_bfm_v2_0_ocm_mem.v" \
    "$ref_dir/./../../../../zynq-memory-ordering.srcs/sources_1/bd/block_diagram/ipshared/xilinx.com/processing_system7_bfm_v2_0/hdl/processing_system7_bfm_v2_0_intr_wr_mem.v" \
    "$ref_dir/./../../../../zynq-memory-ordering.srcs/sources_1/bd/block_diagram/ipshared/xilinx.com/processing_system7_bfm_v2_0/hdl/processing_system7_bfm_v2_0_intr_rd_mem.v" \
    "$ref_dir/./../../../../zynq-memory-ordering.srcs/sources_1/bd/block_diagram/ipshared/xilinx.com/processing_system7_bfm_v2_0/hdl/processing_system7_bfm_v2_0_fmsw_gp.v" \
    "$ref_dir/./../../../../zynq-memory-ordering.srcs/sources_1/bd/block_diagram/ipshared/xilinx.com/processing_system7_bfm_v2_0/hdl/processing_system7_bfm_v2_0_regc.v" \
    "$ref_dir/./../../../../zynq-memory-ordering.srcs/sources_1/bd/block_diagram/ipshared/xilinx.com/processing_system7_bfm_v2_0/hdl/processing_system7_bfm_v2_0_ocmc.v" \
    "$ref_dir/./../../../../zynq-memory-ordering.srcs/sources_1/bd/block_diagram/ipshared/xilinx.com/processing_system7_bfm_v2_0/hdl/processing_system7_bfm_v2_0_interconnect_model.v" \
    "$ref_dir/./../../../../zynq-memory-ordering.srcs/sources_1/bd/block_diagram/ipshared/xilinx.com/processing_system7_bfm_v2_0/hdl/processing_system7_bfm_v2_0_gen_reset.v" \
    "$ref_dir/./../../../../zynq-memory-ordering.srcs/sources_1/bd/block_diagram/ipshared/xilinx.com/processing_system7_bfm_v2_0/hdl/processing_system7_bfm_v2_0_gen_clock.v" \
    "$ref_dir/./../../../../zynq-memory-ordering.srcs/sources_1/bd/block_diagram/ipshared/xilinx.com/processing_system7_bfm_v2_0/hdl/processing_system7_bfm_v2_0_ddrc.v" \
    "$ref_dir/./../../../../zynq-memory-ordering.srcs/sources_1/bd/block_diagram/ipshared/xilinx.com/processing_system7_bfm_v2_0/hdl/processing_system7_bfm_v2_0_axi_slave.v" \
    "$ref_dir/./../../../../zynq-memory-ordering.srcs/sources_1/bd/block_diagram/ipshared/xilinx.com/processing_system7_bfm_v2_0/hdl/processing_system7_bfm_v2_0_axi_master.v" \
    "$ref_dir/./../../../../zynq-memory-ordering.srcs/sources_1/bd/block_diagram/ipshared/xilinx.com/processing_system7_bfm_v2_0/hdl/processing_system7_bfm_v2_0_afi_slave.v" \
    "$ref_dir/./../../../../zynq-memory-ordering.srcs/sources_1/bd/block_diagram/ipshared/xilinx.com/processing_system7_bfm_v2_0/hdl/processing_system7_bfm_v2_0_processing_system7_bfm.v" \
    "$ref_dir/./../../../bd/block_diagram/ip/block_diagram_processing_system7_0_0/sim/block_diagram_processing_system7_0_0.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work lib_cdc_v1_0_2 $opts_vhd \
    "$ref_dir/./../../../../zynq-memory-ordering.srcs/sources_1/bd/block_diagram/ipshared/xilinx.com/lib_cdc_v1_0/hdl/src/vhdl/cdc_sync.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work proc_sys_reset_v5_0_8 $opts_vhd \
    "$ref_dir/./../../../../zynq-memory-ordering.srcs/sources_1/bd/block_diagram/ipshared/xilinx.com/proc_sys_reset_v5_0/hdl/src/vhdl/upcnt_n.vhd" \
    "$ref_dir/./../../../../zynq-memory-ordering.srcs/sources_1/bd/block_diagram/ipshared/xilinx.com/proc_sys_reset_v5_0/hdl/src/vhdl/sequence_psr.vhd" \
    "$ref_dir/./../../../../zynq-memory-ordering.srcs/sources_1/bd/block_diagram/ipshared/xilinx.com/proc_sys_reset_v5_0/hdl/src/vhdl/lpf.vhd" \
    "$ref_dir/./../../../../zynq-memory-ordering.srcs/sources_1/bd/block_diagram/ipshared/xilinx.com/proc_sys_reset_v5_0/hdl/src/vhdl/proc_sys_reset.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $opts_vhd \
    "$ref_dir/./../../../bd/block_diagram/ip/block_diagram_proc_sys_reset_0_0/sim/block_diagram_proc_sys_reset_0_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $opts_ver +v2k +incdir+"$ref_dir/../../../../zynq-memory-ordering.srcs/sources_1/bd/block_diagram/ipshared/xilinx.com/axi_infrastructure_v1_1/hdl/verilog" +incdir+"$ref_dir/../../../../zynq-memory-ordering.srcs/sources_1/bd/block_diagram/ipshared/xilinx.com/processing_system7_bfm_v2_0/hdl" +incdir+"$ref_dir/../../../bd/block_diagram/ip/block_diagram_processing_system7_0_0" +incdir+"$ref_dir/../../../bd/block_diagram/ipshared/xilinx.com/ila_v6_0/hdl/verilog" +incdir+"$ref_dir/../../../bd/block_diagram/ipshared/xilinx.com/ltlib_v1_0/hdl/verilog" +incdir+"$ref_dir/../../../bd/block_diagram/ipshared/xilinx.com/xsdbm_v1_1/hdl/verilog" +incdir+"$ref_dir/../../../bd/block_diagram/ipshared/xilinx.com/xsdbs_v1_0/hdl/verilog" +incdir+"$ref_dir/../../../../zynq-memory-ordering.srcs/sources_1/bd/block_diagram/ip/block_diagram_processing_system7_0_0" +incdir+"$ref_dir/../../../../zynq-memory-ordering.srcs/sources_1/bd/block_diagram/ipshared/user.org/hardware_accelerator_v1_0/drivers/hardware-accelerator_v1_0/src" +incdir+"$ref_dir/../../../../zynq-memory-ordering.srcs/sources_1/bd/block_diagram/ipshared/xilinx.com/axi4_metrics_counter_v1_0/drivers/axi3_metrics_counter_v1_0/src" +incdir+"$ref_dir/../../../../zynq-memory-ordering.srcs/sources_1/bd/block_diagram/ipshared/xilinx.com/ila_v6_0/hdl/verilog" +incdir+"$ref_dir/../../../../zynq-memory-ordering.srcs/sources_1/bd/block_diagram/ipshared/xilinx.com/ltlib_v1_0/hdl/verilog" +incdir+"$ref_dir/../../../../zynq-memory-ordering.srcs/sources_1/bd/block_diagram/ipshared/xilinx.com/xsdbm_v1_1/hdl/verilog" +incdir+"$ref_dir/../../../../zynq-memory-ordering.srcs/sources_1/bd/block_diagram/ipshared/xilinx.com/xsdbs_v1_0/hdl/verilog" +incdir+"$ref_dir/../../../ipstatic/axi_infrastructure_v1_1/hdl/verilog" +incdir+"$ref_dir/../../../ipstatic/processing_system7_bfm_v2_0/hdl" \
    "$ref_dir/./../../../bd/block_diagram/ipshared/user.org/hardware_accelerator_v1_0/hdl/registers_module.v" \
    "$ref_dir/./../../../bd/block_diagram/ipshared/user.org/hardware_accelerator_v1_0/hdl/controller_module.v" \
    "$ref_dir/./../../../bd/block_diagram/ipshared/user.org/hardware_accelerator_v1_0/hdl/data_module.v" \
    "$ref_dir/./../../../bd/block_diagram/ipshared/user.org/hardware_accelerator_v1_0/hdl/hardware-accelerator_v1_0.v" \
    "$ref_dir/./../../../bd/block_diagram/ip/block_diagram_hardware_accelerator_0_0/sim/block_diagram_hardware_accelerator_0_0.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work generic_baseblocks_v2_1_0 $opts_ver +v2k +incdir+"$ref_dir/../../../../zynq-memory-ordering.srcs/sources_1/bd/block_diagram/ipshared/xilinx.com/axi_infrastructure_v1_1/hdl/verilog" +incdir+"$ref_dir/../../../../zynq-memory-ordering.srcs/sources_1/bd/block_diagram/ipshared/xilinx.com/processing_system7_bfm_v2_0/hdl" +incdir+"$ref_dir/../../../bd/block_diagram/ip/block_diagram_processing_system7_0_0" +incdir+"$ref_dir/../../../bd/block_diagram/ipshared/xilinx.com/ila_v6_0/hdl/verilog" +incdir+"$ref_dir/../../../bd/block_diagram/ipshared/xilinx.com/ltlib_v1_0/hdl/verilog" +incdir+"$ref_dir/../../../bd/block_diagram/ipshared/xilinx.com/xsdbm_v1_1/hdl/verilog" +incdir+"$ref_dir/../../../bd/block_diagram/ipshared/xilinx.com/xsdbs_v1_0/hdl/verilog" +incdir+"$ref_dir/../../../../zynq-memory-ordering.srcs/sources_1/bd/block_diagram/ip/block_diagram_processing_system7_0_0" +incdir+"$ref_dir/../../../../zynq-memory-ordering.srcs/sources_1/bd/block_diagram/ipshared/user.org/hardware_accelerator_v1_0/drivers/hardware-accelerator_v1_0/src" +incdir+"$ref_dir/../../../../zynq-memory-ordering.srcs/sources_1/bd/block_diagram/ipshared/xilinx.com/axi4_metrics_counter_v1_0/drivers/axi3_metrics_counter_v1_0/src" +incdir+"$ref_dir/../../../../zynq-memory-ordering.srcs/sources_1/bd/block_diagram/ipshared/xilinx.com/ila_v6_0/hdl/verilog" +incdir+"$ref_dir/../../../../zynq-memory-ordering.srcs/sources_1/bd/block_diagram/ipshared/xilinx.com/ltlib_v1_0/hdl/verilog" +incdir+"$ref_dir/../../../../zynq-memory-ordering.srcs/sources_1/bd/block_diagram/ipshared/xilinx.com/xsdbm_v1_1/hdl/verilog" +incdir+"$ref_dir/../../../../zynq-memory-ordering.srcs/sources_1/bd/block_diagram/ipshared/xilinx.com/xsdbs_v1_0/hdl/verilog" +incdir+"$ref_dir/../../../ipstatic/axi_infrastructure_v1_1/hdl/verilog" +incdir+"$ref_dir/../../../ipstatic/processing_system7_bfm_v2_0/hdl" \
    "$ref_dir/./../../../../zynq-memory-ordering.srcs/sources_1/bd/block_diagram/ipshared/xilinx.com/generic_baseblocks_v2_1/hdl/verilog/generic_baseblocks_v2_1_carry_and.v" \
    "$ref_dir/./../../../../zynq-memory-ordering.srcs/sources_1/bd/block_diagram/ipshared/xilinx.com/generic_baseblocks_v2_1/hdl/verilog/generic_baseblocks_v2_1_carry_latch_and.v" \
    "$ref_dir/./../../../../zynq-memory-ordering.srcs/sources_1/bd/block_diagram/ipshared/xilinx.com/generic_baseblocks_v2_1/hdl/verilog/generic_baseblocks_v2_1_carry_latch_or.v" \
    "$ref_dir/./../../../../zynq-memory-ordering.srcs/sources_1/bd/block_diagram/ipshared/xilinx.com/generic_baseblocks_v2_1/hdl/verilog/generic_baseblocks_v2_1_carry_or.v" \
    "$ref_dir/./../../../../zynq-memory-ordering.srcs/sources_1/bd/block_diagram/ipshared/xilinx.com/generic_baseblocks_v2_1/hdl/verilog/generic_baseblocks_v2_1_carry.v" \
    "$ref_dir/./../../../../zynq-memory-ordering.srcs/sources_1/bd/block_diagram/ipshared/xilinx.com/generic_baseblocks_v2_1/hdl/verilog/generic_baseblocks_v2_1_command_fifo.v" \
    "$ref_dir/./../../../../zynq-memory-ordering.srcs/sources_1/bd/block_diagram/ipshared/xilinx.com/generic_baseblocks_v2_1/hdl/verilog/generic_baseblocks_v2_1_comparator_mask_static.v" \
    "$ref_dir/./../../../../zynq-memory-ordering.srcs/sources_1/bd/block_diagram/ipshared/xilinx.com/generic_baseblocks_v2_1/hdl/verilog/generic_baseblocks_v2_1_comparator_mask.v" \
    "$ref_dir/./../../../../zynq-memory-ordering.srcs/sources_1/bd/block_diagram/ipshared/xilinx.com/generic_baseblocks_v2_1/hdl/verilog/generic_baseblocks_v2_1_comparator_sel_mask_static.v" \
    "$ref_dir/./../../../../zynq-memory-ordering.srcs/sources_1/bd/block_diagram/ipshared/xilinx.com/generic_baseblocks_v2_1/hdl/verilog/generic_baseblocks_v2_1_comparator_sel_mask.v" \
    "$ref_dir/./../../../../zynq-memory-ordering.srcs/sources_1/bd/block_diagram/ipshared/xilinx.com/generic_baseblocks_v2_1/hdl/verilog/generic_baseblocks_v2_1_comparator_sel_static.v" \
    "$ref_dir/./../../../../zynq-memory-ordering.srcs/sources_1/bd/block_diagram/ipshared/xilinx.com/generic_baseblocks_v2_1/hdl/verilog/generic_baseblocks_v2_1_comparator_sel.v" \
    "$ref_dir/./../../../../zynq-memory-ordering.srcs/sources_1/bd/block_diagram/ipshared/xilinx.com/generic_baseblocks_v2_1/hdl/verilog/generic_baseblocks_v2_1_comparator_static.v" \
    "$ref_dir/./../../../../zynq-memory-ordering.srcs/sources_1/bd/block_diagram/ipshared/xilinx.com/generic_baseblocks_v2_1/hdl/verilog/generic_baseblocks_v2_1_comparator.v" \
    "$ref_dir/./../../../../zynq-memory-ordering.srcs/sources_1/bd/block_diagram/ipshared/xilinx.com/generic_baseblocks_v2_1/hdl/verilog/generic_baseblocks_v2_1_mux_enc.v" \
    "$ref_dir/./../../../../zynq-memory-ordering.srcs/sources_1/bd/block_diagram/ipshared/xilinx.com/generic_baseblocks_v2_1/hdl/verilog/generic_baseblocks_v2_1_mux.v" \
    "$ref_dir/./../../../../zynq-memory-ordering.srcs/sources_1/bd/block_diagram/ipshared/xilinx.com/generic_baseblocks_v2_1/hdl/verilog/generic_baseblocks_v2_1_nto1_mux.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_infrastructure_v1_1_0 $opts_ver +v2k +incdir+"$ref_dir/../../../../zynq-memory-ordering.srcs/sources_1/bd/block_diagram/ipshared/xilinx.com/axi_infrastructure_v1_1/hdl/verilog" +incdir+"$ref_dir/../../../../zynq-memory-ordering.srcs/sources_1/bd/block_diagram/ipshared/xilinx.com/processing_system7_bfm_v2_0/hdl" +incdir+"$ref_dir/../../../bd/block_diagram/ip/block_diagram_processing_system7_0_0" +incdir+"$ref_dir/../../../bd/block_diagram/ipshared/xilinx.com/ila_v6_0/hdl/verilog" +incdir+"$ref_dir/../../../bd/block_diagram/ipshared/xilinx.com/ltlib_v1_0/hdl/verilog" +incdir+"$ref_dir/../../../bd/block_diagram/ipshared/xilinx.com/xsdbm_v1_1/hdl/verilog" +incdir+"$ref_dir/../../../bd/block_diagram/ipshared/xilinx.com/xsdbs_v1_0/hdl/verilog" +incdir+"$ref_dir/../../../../zynq-memory-ordering.srcs/sources_1/bd/block_diagram/ip/block_diagram_processing_system7_0_0" +incdir+"$ref_dir/../../../../zynq-memory-ordering.srcs/sources_1/bd/block_diagram/ipshared/user.org/hardware_accelerator_v1_0/drivers/hardware-accelerator_v1_0/src" +incdir+"$ref_dir/../../../../zynq-memory-ordering.srcs/sources_1/bd/block_diagram/ipshared/xilinx.com/axi4_metrics_counter_v1_0/drivers/axi3_metrics_counter_v1_0/src" +incdir+"$ref_dir/../../../../zynq-memory-ordering.srcs/sources_1/bd/block_diagram/ipshared/xilinx.com/ila_v6_0/hdl/verilog" +incdir+"$ref_dir/../../../../zynq-memory-ordering.srcs/sources_1/bd/block_diagram/ipshared/xilinx.com/ltlib_v1_0/hdl/verilog" +incdir+"$ref_dir/../../../../zynq-memory-ordering.srcs/sources_1/bd/block_diagram/ipshared/xilinx.com/xsdbm_v1_1/hdl/verilog" +incdir+"$ref_dir/../../../../zynq-memory-ordering.srcs/sources_1/bd/block_diagram/ipshared/xilinx.com/xsdbs_v1_0/hdl/verilog" +incdir+"$ref_dir/../../../ipstatic/axi_infrastructure_v1_1/hdl/verilog" +incdir+"$ref_dir/../../../ipstatic/processing_system7_bfm_v2_0/hdl" \
    "$ref_dir/./../../../../zynq-memory-ordering.srcs/sources_1/bd/block_diagram/ipshared/xilinx.com/axi_infrastructure_v1_1/hdl/verilog/axi_infrastructure_v1_1_axi2vector.v" \
    "$ref_dir/./../../../../zynq-memory-ordering.srcs/sources_1/bd/block_diagram/ipshared/xilinx.com/axi_infrastructure_v1_1/hdl/verilog/axi_infrastructure_v1_1_axic_srl_fifo.v" \
    "$ref_dir/./../../../../zynq-memory-ordering.srcs/sources_1/bd/block_diagram/ipshared/xilinx.com/axi_infrastructure_v1_1/hdl/verilog/axi_infrastructure_v1_1_vector2axi.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_register_slice_v2_1_6 $opts_ver +v2k +incdir+"$ref_dir/../../../../zynq-memory-ordering.srcs/sources_1/bd/block_diagram/ipshared/xilinx.com/axi_infrastructure_v1_1/hdl/verilog" +incdir+"$ref_dir/../../../../zynq-memory-ordering.srcs/sources_1/bd/block_diagram/ipshared/xilinx.com/processing_system7_bfm_v2_0/hdl" +incdir+"$ref_dir/../../../bd/block_diagram/ip/block_diagram_processing_system7_0_0" +incdir+"$ref_dir/../../../bd/block_diagram/ipshared/xilinx.com/ila_v6_0/hdl/verilog" +incdir+"$ref_dir/../../../bd/block_diagram/ipshared/xilinx.com/ltlib_v1_0/hdl/verilog" +incdir+"$ref_dir/../../../bd/block_diagram/ipshared/xilinx.com/xsdbm_v1_1/hdl/verilog" +incdir+"$ref_dir/../../../bd/block_diagram/ipshared/xilinx.com/xsdbs_v1_0/hdl/verilog" +incdir+"$ref_dir/../../../../zynq-memory-ordering.srcs/sources_1/bd/block_diagram/ip/block_diagram_processing_system7_0_0" +incdir+"$ref_dir/../../../../zynq-memory-ordering.srcs/sources_1/bd/block_diagram/ipshared/user.org/hardware_accelerator_v1_0/drivers/hardware-accelerator_v1_0/src" +incdir+"$ref_dir/../../../../zynq-memory-ordering.srcs/sources_1/bd/block_diagram/ipshared/xilinx.com/axi4_metrics_counter_v1_0/drivers/axi3_metrics_counter_v1_0/src" +incdir+"$ref_dir/../../../../zynq-memory-ordering.srcs/sources_1/bd/block_diagram/ipshared/xilinx.com/ila_v6_0/hdl/verilog" +incdir+"$ref_dir/../../../../zynq-memory-ordering.srcs/sources_1/bd/block_diagram/ipshared/xilinx.com/ltlib_v1_0/hdl/verilog" +incdir+"$ref_dir/../../../../zynq-memory-ordering.srcs/sources_1/bd/block_diagram/ipshared/xilinx.com/xsdbm_v1_1/hdl/verilog" +incdir+"$ref_dir/../../../../zynq-memory-ordering.srcs/sources_1/bd/block_diagram/ipshared/xilinx.com/xsdbs_v1_0/hdl/verilog" +incdir+"$ref_dir/../../../ipstatic/axi_infrastructure_v1_1/hdl/verilog" +incdir+"$ref_dir/../../../ipstatic/processing_system7_bfm_v2_0/hdl" \
    "$ref_dir/./../../../../zynq-memory-ordering.srcs/sources_1/bd/block_diagram/ipshared/xilinx.com/axi_register_slice_v2_1/hdl/verilog/axi_register_slice_v2_1_axic_register_slice.v" \
    "$ref_dir/./../../../../zynq-memory-ordering.srcs/sources_1/bd/block_diagram/ipshared/xilinx.com/axi_register_slice_v2_1/hdl/verilog/axi_register_slice_v2_1_axi_register_slice.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work fifo_generator_v13_0_0 $opts_vhd \
    "$ref_dir/./../../../../zynq-memory-ordering.srcs/sources_1/bd/block_diagram/ipshared/xilinx.com/fifo_generator_v13_0/simulation/fifo_generator_vhdl_beh.vhd" \
    "$ref_dir/./../../../../zynq-memory-ordering.srcs/sources_1/bd/block_diagram/ipshared/xilinx.com/fifo_generator_v13_0/hdl/fifo_generator_v13_0_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work axi_data_fifo_v2_1_5 $opts_ver +v2k +incdir+"$ref_dir/../../../../zynq-memory-ordering.srcs/sources_1/bd/block_diagram/ipshared/xilinx.com/axi_infrastructure_v1_1/hdl/verilog" +incdir+"$ref_dir/../../../../zynq-memory-ordering.srcs/sources_1/bd/block_diagram/ipshared/xilinx.com/processing_system7_bfm_v2_0/hdl" +incdir+"$ref_dir/../../../bd/block_diagram/ip/block_diagram_processing_system7_0_0" +incdir+"$ref_dir/../../../bd/block_diagram/ipshared/xilinx.com/ila_v6_0/hdl/verilog" +incdir+"$ref_dir/../../../bd/block_diagram/ipshared/xilinx.com/ltlib_v1_0/hdl/verilog" +incdir+"$ref_dir/../../../bd/block_diagram/ipshared/xilinx.com/xsdbm_v1_1/hdl/verilog" +incdir+"$ref_dir/../../../bd/block_diagram/ipshared/xilinx.com/xsdbs_v1_0/hdl/verilog" +incdir+"$ref_dir/../../../../zynq-memory-ordering.srcs/sources_1/bd/block_diagram/ip/block_diagram_processing_system7_0_0" +incdir+"$ref_dir/../../../../zynq-memory-ordering.srcs/sources_1/bd/block_diagram/ipshared/user.org/hardware_accelerator_v1_0/drivers/hardware-accelerator_v1_0/src" +incdir+"$ref_dir/../../../../zynq-memory-ordering.srcs/sources_1/bd/block_diagram/ipshared/xilinx.com/axi4_metrics_counter_v1_0/drivers/axi3_metrics_counter_v1_0/src" +incdir+"$ref_dir/../../../../zynq-memory-ordering.srcs/sources_1/bd/block_diagram/ipshared/xilinx.com/ila_v6_0/hdl/verilog" +incdir+"$ref_dir/../../../../zynq-memory-ordering.srcs/sources_1/bd/block_diagram/ipshared/xilinx.com/ltlib_v1_0/hdl/verilog" +incdir+"$ref_dir/../../../../zynq-memory-ordering.srcs/sources_1/bd/block_diagram/ipshared/xilinx.com/xsdbm_v1_1/hdl/verilog" +incdir+"$ref_dir/../../../../zynq-memory-ordering.srcs/sources_1/bd/block_diagram/ipshared/xilinx.com/xsdbs_v1_0/hdl/verilog" +incdir+"$ref_dir/../../../ipstatic/axi_infrastructure_v1_1/hdl/verilog" +incdir+"$ref_dir/../../../ipstatic/processing_system7_bfm_v2_0/hdl" \
    "$ref_dir/./../../../../zynq-memory-ordering.srcs/sources_1/bd/block_diagram/ipshared/xilinx.com/axi_data_fifo_v2_1/hdl/verilog/axi_data_fifo_v2_1_axic_fifo.v" \
    "$ref_dir/./../../../../zynq-memory-ordering.srcs/sources_1/bd/block_diagram/ipshared/xilinx.com/axi_data_fifo_v2_1/hdl/verilog/axi_data_fifo_v2_1_fifo_gen.v" \
    "$ref_dir/./../../../../zynq-memory-ordering.srcs/sources_1/bd/block_diagram/ipshared/xilinx.com/axi_data_fifo_v2_1/hdl/verilog/axi_data_fifo_v2_1_axic_srl_fifo.v" \
    "$ref_dir/./../../../../zynq-memory-ordering.srcs/sources_1/bd/block_diagram/ipshared/xilinx.com/axi_data_fifo_v2_1/hdl/verilog/axi_data_fifo_v2_1_axic_reg_srl_fifo.v" \
    "$ref_dir/./../../../../zynq-memory-ordering.srcs/sources_1/bd/block_diagram/ipshared/xilinx.com/axi_data_fifo_v2_1/hdl/verilog/axi_data_fifo_v2_1_ndeep_srl.v" \
    "$ref_dir/./../../../../zynq-memory-ordering.srcs/sources_1/bd/block_diagram/ipshared/xilinx.com/axi_data_fifo_v2_1/hdl/verilog/axi_data_fifo_v2_1_axi_data_fifo.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_crossbar_v2_1_7 $opts_ver +v2k +incdir+"$ref_dir/../../../../zynq-memory-ordering.srcs/sources_1/bd/block_diagram/ipshared/xilinx.com/axi_infrastructure_v1_1/hdl/verilog" +incdir+"$ref_dir/../../../../zynq-memory-ordering.srcs/sources_1/bd/block_diagram/ipshared/xilinx.com/processing_system7_bfm_v2_0/hdl" +incdir+"$ref_dir/../../../bd/block_diagram/ip/block_diagram_processing_system7_0_0" +incdir+"$ref_dir/../../../bd/block_diagram/ipshared/xilinx.com/ila_v6_0/hdl/verilog" +incdir+"$ref_dir/../../../bd/block_diagram/ipshared/xilinx.com/ltlib_v1_0/hdl/verilog" +incdir+"$ref_dir/../../../bd/block_diagram/ipshared/xilinx.com/xsdbm_v1_1/hdl/verilog" +incdir+"$ref_dir/../../../bd/block_diagram/ipshared/xilinx.com/xsdbs_v1_0/hdl/verilog" +incdir+"$ref_dir/../../../../zynq-memory-ordering.srcs/sources_1/bd/block_diagram/ip/block_diagram_processing_system7_0_0" +incdir+"$ref_dir/../../../../zynq-memory-ordering.srcs/sources_1/bd/block_diagram/ipshared/user.org/hardware_accelerator_v1_0/drivers/hardware-accelerator_v1_0/src" +incdir+"$ref_dir/../../../../zynq-memory-ordering.srcs/sources_1/bd/block_diagram/ipshared/xilinx.com/axi4_metrics_counter_v1_0/drivers/axi3_metrics_counter_v1_0/src" +incdir+"$ref_dir/../../../../zynq-memory-ordering.srcs/sources_1/bd/block_diagram/ipshared/xilinx.com/ila_v6_0/hdl/verilog" +incdir+"$ref_dir/../../../../zynq-memory-ordering.srcs/sources_1/bd/block_diagram/ipshared/xilinx.com/ltlib_v1_0/hdl/verilog" +incdir+"$ref_dir/../../../../zynq-memory-ordering.srcs/sources_1/bd/block_diagram/ipshared/xilinx.com/xsdbm_v1_1/hdl/verilog" +incdir+"$ref_dir/../../../../zynq-memory-ordering.srcs/sources_1/bd/block_diagram/ipshared/xilinx.com/xsdbs_v1_0/hdl/verilog" +incdir+"$ref_dir/../../../ipstatic/axi_infrastructure_v1_1/hdl/verilog" +incdir+"$ref_dir/../../../ipstatic/processing_system7_bfm_v2_0/hdl" \
    "$ref_dir/./../../../../zynq-memory-ordering.srcs/sources_1/bd/block_diagram/ipshared/xilinx.com/axi_crossbar_v2_1/hdl/verilog/axi_crossbar_v2_1_addr_arbiter_sasd.v" \
    "$ref_dir/./../../../../zynq-memory-ordering.srcs/sources_1/bd/block_diagram/ipshared/xilinx.com/axi_crossbar_v2_1/hdl/verilog/axi_crossbar_v2_1_addr_arbiter.v" \
    "$ref_dir/./../../../../zynq-memory-ordering.srcs/sources_1/bd/block_diagram/ipshared/xilinx.com/axi_crossbar_v2_1/hdl/verilog/axi_crossbar_v2_1_addr_decoder.v" \
    "$ref_dir/./../../../../zynq-memory-ordering.srcs/sources_1/bd/block_diagram/ipshared/xilinx.com/axi_crossbar_v2_1/hdl/verilog/axi_crossbar_v2_1_arbiter_resp.v" \
    "$ref_dir/./../../../../zynq-memory-ordering.srcs/sources_1/bd/block_diagram/ipshared/xilinx.com/axi_crossbar_v2_1/hdl/verilog/axi_crossbar_v2_1_crossbar_sasd.v" \
    "$ref_dir/./../../../../zynq-memory-ordering.srcs/sources_1/bd/block_diagram/ipshared/xilinx.com/axi_crossbar_v2_1/hdl/verilog/axi_crossbar_v2_1_crossbar.v" \
    "$ref_dir/./../../../../zynq-memory-ordering.srcs/sources_1/bd/block_diagram/ipshared/xilinx.com/axi_crossbar_v2_1/hdl/verilog/axi_crossbar_v2_1_decerr_slave.v" \
    "$ref_dir/./../../../../zynq-memory-ordering.srcs/sources_1/bd/block_diagram/ipshared/xilinx.com/axi_crossbar_v2_1/hdl/verilog/axi_crossbar_v2_1_si_transactor.v" \
    "$ref_dir/./../../../../zynq-memory-ordering.srcs/sources_1/bd/block_diagram/ipshared/xilinx.com/axi_crossbar_v2_1/hdl/verilog/axi_crossbar_v2_1_splitter.v" \
    "$ref_dir/./../../../../zynq-memory-ordering.srcs/sources_1/bd/block_diagram/ipshared/xilinx.com/axi_crossbar_v2_1/hdl/verilog/axi_crossbar_v2_1_wdata_mux.v" \
    "$ref_dir/./../../../../zynq-memory-ordering.srcs/sources_1/bd/block_diagram/ipshared/xilinx.com/axi_crossbar_v2_1/hdl/verilog/axi_crossbar_v2_1_wdata_router.v" \
    "$ref_dir/./../../../../zynq-memory-ordering.srcs/sources_1/bd/block_diagram/ipshared/xilinx.com/axi_crossbar_v2_1/hdl/verilog/axi_crossbar_v2_1_axi_crossbar.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $opts_ver +v2k +incdir+"$ref_dir/../../../../zynq-memory-ordering.srcs/sources_1/bd/block_diagram/ipshared/xilinx.com/axi_infrastructure_v1_1/hdl/verilog" +incdir+"$ref_dir/../../../../zynq-memory-ordering.srcs/sources_1/bd/block_diagram/ipshared/xilinx.com/processing_system7_bfm_v2_0/hdl" +incdir+"$ref_dir/../../../bd/block_diagram/ip/block_diagram_processing_system7_0_0" +incdir+"$ref_dir/../../../bd/block_diagram/ipshared/xilinx.com/ila_v6_0/hdl/verilog" +incdir+"$ref_dir/../../../bd/block_diagram/ipshared/xilinx.com/ltlib_v1_0/hdl/verilog" +incdir+"$ref_dir/../../../bd/block_diagram/ipshared/xilinx.com/xsdbm_v1_1/hdl/verilog" +incdir+"$ref_dir/../../../bd/block_diagram/ipshared/xilinx.com/xsdbs_v1_0/hdl/verilog" +incdir+"$ref_dir/../../../../zynq-memory-ordering.srcs/sources_1/bd/block_diagram/ip/block_diagram_processing_system7_0_0" +incdir+"$ref_dir/../../../../zynq-memory-ordering.srcs/sources_1/bd/block_diagram/ipshared/user.org/hardware_accelerator_v1_0/drivers/hardware-accelerator_v1_0/src" +incdir+"$ref_dir/../../../../zynq-memory-ordering.srcs/sources_1/bd/block_diagram/ipshared/xilinx.com/axi4_metrics_counter_v1_0/drivers/axi3_metrics_counter_v1_0/src" +incdir+"$ref_dir/../../../../zynq-memory-ordering.srcs/sources_1/bd/block_diagram/ipshared/xilinx.com/ila_v6_0/hdl/verilog" +incdir+"$ref_dir/../../../../zynq-memory-ordering.srcs/sources_1/bd/block_diagram/ipshared/xilinx.com/ltlib_v1_0/hdl/verilog" +incdir+"$ref_dir/../../../../zynq-memory-ordering.srcs/sources_1/bd/block_diagram/ipshared/xilinx.com/xsdbm_v1_1/hdl/verilog" +incdir+"$ref_dir/../../../../zynq-memory-ordering.srcs/sources_1/bd/block_diagram/ipshared/xilinx.com/xsdbs_v1_0/hdl/verilog" +incdir+"$ref_dir/../../../ipstatic/axi_infrastructure_v1_1/hdl/verilog" +incdir+"$ref_dir/../../../ipstatic/processing_system7_bfm_v2_0/hdl" \
    "$ref_dir/./../../../bd/block_diagram/ip/block_diagram_xbar_0/sim/block_diagram_xbar_0.v" \
    "$ref_dir/./../../../bd/block_diagram/ipshared/xilinx.com/axi4_metrics_counter_v1_0/hdl/axi3_metrics_counter_v1_0.v" \
    "$ref_dir/./../../../bd/block_diagram/ip/block_diagram_axi4_metrics_counter_0_0/sim/block_diagram_axi4_metrics_counter_0_0.v" \
    "$ref_dir/./../../../bd/block_diagram/ipshared/xilinx.com/xlslice_v1_0/xlslice.v" \
    "$ref_dir/./../../../bd/block_diagram/ip/block_diagram_xlslice_0_0/sim/block_diagram_xlslice_0_0.v" \
    "$ref_dir/./../../../bd/block_diagram/ip/block_diagram_xlslice_0_1/sim/block_diagram_xlslice_0_1.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work util_reduced_logic_v2_0 $opts_vhd \
    "$ref_dir/./../../../bd/block_diagram/ipshared/xilinx.com/util_reduced_logic_v2_0/hdl/util_reduced_logic.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $opts_vhd \
    "$ref_dir/./../../../bd/block_diagram/ip/block_diagram_util_reduced_logic_0_0/sim/block_diagram_util_reduced_logic_0_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $opts_ver +v2k +incdir+"$ref_dir/../../../../zynq-memory-ordering.srcs/sources_1/bd/block_diagram/ipshared/xilinx.com/axi_infrastructure_v1_1/hdl/verilog" +incdir+"$ref_dir/../../../../zynq-memory-ordering.srcs/sources_1/bd/block_diagram/ipshared/xilinx.com/processing_system7_bfm_v2_0/hdl" +incdir+"$ref_dir/../../../bd/block_diagram/ip/block_diagram_processing_system7_0_0" +incdir+"$ref_dir/../../../bd/block_diagram/ipshared/xilinx.com/ila_v6_0/hdl/verilog" +incdir+"$ref_dir/../../../bd/block_diagram/ipshared/xilinx.com/ltlib_v1_0/hdl/verilog" +incdir+"$ref_dir/../../../bd/block_diagram/ipshared/xilinx.com/xsdbm_v1_1/hdl/verilog" +incdir+"$ref_dir/../../../bd/block_diagram/ipshared/xilinx.com/xsdbs_v1_0/hdl/verilog" +incdir+"$ref_dir/../../../../zynq-memory-ordering.srcs/sources_1/bd/block_diagram/ip/block_diagram_processing_system7_0_0" +incdir+"$ref_dir/../../../../zynq-memory-ordering.srcs/sources_1/bd/block_diagram/ipshared/user.org/hardware_accelerator_v1_0/drivers/hardware-accelerator_v1_0/src" +incdir+"$ref_dir/../../../../zynq-memory-ordering.srcs/sources_1/bd/block_diagram/ipshared/xilinx.com/axi4_metrics_counter_v1_0/drivers/axi3_metrics_counter_v1_0/src" +incdir+"$ref_dir/../../../../zynq-memory-ordering.srcs/sources_1/bd/block_diagram/ipshared/xilinx.com/ila_v6_0/hdl/verilog" +incdir+"$ref_dir/../../../../zynq-memory-ordering.srcs/sources_1/bd/block_diagram/ipshared/xilinx.com/ltlib_v1_0/hdl/verilog" +incdir+"$ref_dir/../../../../zynq-memory-ordering.srcs/sources_1/bd/block_diagram/ipshared/xilinx.com/xsdbm_v1_1/hdl/verilog" +incdir+"$ref_dir/../../../../zynq-memory-ordering.srcs/sources_1/bd/block_diagram/ipshared/xilinx.com/xsdbs_v1_0/hdl/verilog" +incdir+"$ref_dir/../../../ipstatic/axi_infrastructure_v1_1/hdl/verilog" +incdir+"$ref_dir/../../../ipstatic/processing_system7_bfm_v2_0/hdl" \
    "$ref_dir/./../../../bd/block_diagram/ipshared/xilinx.com/xlconcat_v2_1/xlconcat.v" \
    "$ref_dir/./../../../bd/block_diagram/ip/block_diagram_xlconcat_0_0/sim/block_diagram_xlconcat_0_0.v" \
    "$ref_dir/./../../../bd/block_diagram/ip/block_diagram_xlslice_0_2/sim/block_diagram_xlslice_0_2.v" \
    "$ref_dir/./../../../bd/block_diagram/ip/block_diagram_xlslice_0_3/sim/block_diagram_xlslice_0_3.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work util_vector_logic_v2_0 $opts_vhd \
    "$ref_dir/./../../../bd/block_diagram/ipshared/xilinx.com/util_vector_logic_v2_0/hdl/util_vector_logic.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $opts_vhd \
    "$ref_dir/./../../../bd/block_diagram/ip/block_diagram_util_vector_logic_0_0/sim/block_diagram_util_vector_logic_0_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $opts_ver +v2k +incdir+"$ref_dir/../../../../zynq-memory-ordering.srcs/sources_1/bd/block_diagram/ipshared/xilinx.com/axi_infrastructure_v1_1/hdl/verilog" +incdir+"$ref_dir/../../../../zynq-memory-ordering.srcs/sources_1/bd/block_diagram/ipshared/xilinx.com/processing_system7_bfm_v2_0/hdl" +incdir+"$ref_dir/../../../bd/block_diagram/ip/block_diagram_processing_system7_0_0" +incdir+"$ref_dir/../../../bd/block_diagram/ipshared/xilinx.com/ila_v6_0/hdl/verilog" +incdir+"$ref_dir/../../../bd/block_diagram/ipshared/xilinx.com/ltlib_v1_0/hdl/verilog" +incdir+"$ref_dir/../../../bd/block_diagram/ipshared/xilinx.com/xsdbm_v1_1/hdl/verilog" +incdir+"$ref_dir/../../../bd/block_diagram/ipshared/xilinx.com/xsdbs_v1_0/hdl/verilog" +incdir+"$ref_dir/../../../../zynq-memory-ordering.srcs/sources_1/bd/block_diagram/ip/block_diagram_processing_system7_0_0" +incdir+"$ref_dir/../../../../zynq-memory-ordering.srcs/sources_1/bd/block_diagram/ipshared/user.org/hardware_accelerator_v1_0/drivers/hardware-accelerator_v1_0/src" +incdir+"$ref_dir/../../../../zynq-memory-ordering.srcs/sources_1/bd/block_diagram/ipshared/xilinx.com/axi4_metrics_counter_v1_0/drivers/axi3_metrics_counter_v1_0/src" +incdir+"$ref_dir/../../../../zynq-memory-ordering.srcs/sources_1/bd/block_diagram/ipshared/xilinx.com/ila_v6_0/hdl/verilog" +incdir+"$ref_dir/../../../../zynq-memory-ordering.srcs/sources_1/bd/block_diagram/ipshared/xilinx.com/ltlib_v1_0/hdl/verilog" +incdir+"$ref_dir/../../../../zynq-memory-ordering.srcs/sources_1/bd/block_diagram/ipshared/xilinx.com/xsdbm_v1_1/hdl/verilog" +incdir+"$ref_dir/../../../../zynq-memory-ordering.srcs/sources_1/bd/block_diagram/ipshared/xilinx.com/xsdbs_v1_0/hdl/verilog" +incdir+"$ref_dir/../../../ipstatic/axi_infrastructure_v1_1/hdl/verilog" +incdir+"$ref_dir/../../../ipstatic/processing_system7_bfm_v2_0/hdl" \
    "$ref_dir/./../../../bd/block_diagram/ip/block_diagram_xlconcat_0_1/sim/block_diagram_xlconcat_0_1.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xil_defaultlib $opts_vhd \
    "$ref_dir/./../../../bd/block_diagram/ip/block_diagram_util_vector_logic_1_0/sim/block_diagram_util_vector_logic_1_0.vhd" \
    "$ref_dir/./../../../bd/block_diagram/ip/block_diagram_util_reduced_logic_0_1/sim/block_diagram_util_reduced_logic_0_1.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $opts_ver +v2k +incdir+"$ref_dir/../../../../zynq-memory-ordering.srcs/sources_1/bd/block_diagram/ipshared/xilinx.com/axi_infrastructure_v1_1/hdl/verilog" +incdir+"$ref_dir/../../../../zynq-memory-ordering.srcs/sources_1/bd/block_diagram/ipshared/xilinx.com/processing_system7_bfm_v2_0/hdl" +incdir+"$ref_dir/../../../bd/block_diagram/ip/block_diagram_processing_system7_0_0" +incdir+"$ref_dir/../../../bd/block_diagram/ipshared/xilinx.com/ila_v6_0/hdl/verilog" +incdir+"$ref_dir/../../../bd/block_diagram/ipshared/xilinx.com/ltlib_v1_0/hdl/verilog" +incdir+"$ref_dir/../../../bd/block_diagram/ipshared/xilinx.com/xsdbm_v1_1/hdl/verilog" +incdir+"$ref_dir/../../../bd/block_diagram/ipshared/xilinx.com/xsdbs_v1_0/hdl/verilog" +incdir+"$ref_dir/../../../../zynq-memory-ordering.srcs/sources_1/bd/block_diagram/ip/block_diagram_processing_system7_0_0" +incdir+"$ref_dir/../../../../zynq-memory-ordering.srcs/sources_1/bd/block_diagram/ipshared/user.org/hardware_accelerator_v1_0/drivers/hardware-accelerator_v1_0/src" +incdir+"$ref_dir/../../../../zynq-memory-ordering.srcs/sources_1/bd/block_diagram/ipshared/xilinx.com/axi4_metrics_counter_v1_0/drivers/axi3_metrics_counter_v1_0/src" +incdir+"$ref_dir/../../../../zynq-memory-ordering.srcs/sources_1/bd/block_diagram/ipshared/xilinx.com/ila_v6_0/hdl/verilog" +incdir+"$ref_dir/../../../../zynq-memory-ordering.srcs/sources_1/bd/block_diagram/ipshared/xilinx.com/ltlib_v1_0/hdl/verilog" +incdir+"$ref_dir/../../../../zynq-memory-ordering.srcs/sources_1/bd/block_diagram/ipshared/xilinx.com/xsdbm_v1_1/hdl/verilog" +incdir+"$ref_dir/../../../../zynq-memory-ordering.srcs/sources_1/bd/block_diagram/ipshared/xilinx.com/xsdbs_v1_0/hdl/verilog" +incdir+"$ref_dir/../../../ipstatic/axi_infrastructure_v1_1/hdl/verilog" +incdir+"$ref_dir/../../../ipstatic/processing_system7_bfm_v2_0/hdl" \
    "$ref_dir/./../../../bd/block_diagram/ip/block_diagram_xlconcat_1_1/sim/block_diagram_xlconcat_1_1.v" \
    "$ref_dir/./../../../bd/block_diagram/ip/block_diagram_xlconcat_0_2/sim/block_diagram_xlconcat_0_2.v" \
    "$ref_dir/./../../../bd/block_diagram/ip/block_diagram_ila_0_0/sim/block_diagram_ila_0_0.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_protocol_converter_v2_1_6 $opts_ver +v2k +incdir+"$ref_dir/../../../../zynq-memory-ordering.srcs/sources_1/bd/block_diagram/ipshared/xilinx.com/axi_infrastructure_v1_1/hdl/verilog" +incdir+"$ref_dir/../../../../zynq-memory-ordering.srcs/sources_1/bd/block_diagram/ipshared/xilinx.com/processing_system7_bfm_v2_0/hdl" +incdir+"$ref_dir/../../../bd/block_diagram/ip/block_diagram_processing_system7_0_0" +incdir+"$ref_dir/../../../bd/block_diagram/ipshared/xilinx.com/ila_v6_0/hdl/verilog" +incdir+"$ref_dir/../../../bd/block_diagram/ipshared/xilinx.com/ltlib_v1_0/hdl/verilog" +incdir+"$ref_dir/../../../bd/block_diagram/ipshared/xilinx.com/xsdbm_v1_1/hdl/verilog" +incdir+"$ref_dir/../../../bd/block_diagram/ipshared/xilinx.com/xsdbs_v1_0/hdl/verilog" +incdir+"$ref_dir/../../../../zynq-memory-ordering.srcs/sources_1/bd/block_diagram/ip/block_diagram_processing_system7_0_0" +incdir+"$ref_dir/../../../../zynq-memory-ordering.srcs/sources_1/bd/block_diagram/ipshared/user.org/hardware_accelerator_v1_0/drivers/hardware-accelerator_v1_0/src" +incdir+"$ref_dir/../../../../zynq-memory-ordering.srcs/sources_1/bd/block_diagram/ipshared/xilinx.com/axi4_metrics_counter_v1_0/drivers/axi3_metrics_counter_v1_0/src" +incdir+"$ref_dir/../../../../zynq-memory-ordering.srcs/sources_1/bd/block_diagram/ipshared/xilinx.com/ila_v6_0/hdl/verilog" +incdir+"$ref_dir/../../../../zynq-memory-ordering.srcs/sources_1/bd/block_diagram/ipshared/xilinx.com/ltlib_v1_0/hdl/verilog" +incdir+"$ref_dir/../../../../zynq-memory-ordering.srcs/sources_1/bd/block_diagram/ipshared/xilinx.com/xsdbm_v1_1/hdl/verilog" +incdir+"$ref_dir/../../../../zynq-memory-ordering.srcs/sources_1/bd/block_diagram/ipshared/xilinx.com/xsdbs_v1_0/hdl/verilog" +incdir+"$ref_dir/../../../ipstatic/axi_infrastructure_v1_1/hdl/verilog" +incdir+"$ref_dir/../../../ipstatic/processing_system7_bfm_v2_0/hdl" \
    "$ref_dir/./../../../../zynq-memory-ordering.srcs/sources_1/bd/block_diagram/ipshared/xilinx.com/axi_protocol_converter_v2_1/hdl/verilog/axi_protocol_converter_v2_1_a_axi3_conv.v" \
    "$ref_dir/./../../../../zynq-memory-ordering.srcs/sources_1/bd/block_diagram/ipshared/xilinx.com/axi_protocol_converter_v2_1/hdl/verilog/axi_protocol_converter_v2_1_axi3_conv.v" \
    "$ref_dir/./../../../../zynq-memory-ordering.srcs/sources_1/bd/block_diagram/ipshared/xilinx.com/axi_protocol_converter_v2_1/hdl/verilog/axi_protocol_converter_v2_1_axilite_conv.v" \
    "$ref_dir/./../../../../zynq-memory-ordering.srcs/sources_1/bd/block_diagram/ipshared/xilinx.com/axi_protocol_converter_v2_1/hdl/verilog/axi_protocol_converter_v2_1_r_axi3_conv.v" \
    "$ref_dir/./../../../../zynq-memory-ordering.srcs/sources_1/bd/block_diagram/ipshared/xilinx.com/axi_protocol_converter_v2_1/hdl/verilog/axi_protocol_converter_v2_1_w_axi3_conv.v" \
    "$ref_dir/./../../../../zynq-memory-ordering.srcs/sources_1/bd/block_diagram/ipshared/xilinx.com/axi_protocol_converter_v2_1/hdl/verilog/axi_protocol_converter_v2_1_b_downsizer.v" \
    "$ref_dir/./../../../../zynq-memory-ordering.srcs/sources_1/bd/block_diagram/ipshared/xilinx.com/axi_protocol_converter_v2_1/hdl/verilog/axi_protocol_converter_v2_1_decerr_slave.v" \
    "$ref_dir/./../../../../zynq-memory-ordering.srcs/sources_1/bd/block_diagram/ipshared/xilinx.com/axi_protocol_converter_v2_1/hdl/verilog/axi_protocol_converter_v2_1_b2s_simple_fifo.v" \
    "$ref_dir/./../../../../zynq-memory-ordering.srcs/sources_1/bd/block_diagram/ipshared/xilinx.com/axi_protocol_converter_v2_1/hdl/verilog/axi_protocol_converter_v2_1_b2s_wrap_cmd.v" \
    "$ref_dir/./../../../../zynq-memory-ordering.srcs/sources_1/bd/block_diagram/ipshared/xilinx.com/axi_protocol_converter_v2_1/hdl/verilog/axi_protocol_converter_v2_1_b2s_incr_cmd.v" \
    "$ref_dir/./../../../../zynq-memory-ordering.srcs/sources_1/bd/block_diagram/ipshared/xilinx.com/axi_protocol_converter_v2_1/hdl/verilog/axi_protocol_converter_v2_1_b2s_wr_cmd_fsm.v" \
    "$ref_dir/./../../../../zynq-memory-ordering.srcs/sources_1/bd/block_diagram/ipshared/xilinx.com/axi_protocol_converter_v2_1/hdl/verilog/axi_protocol_converter_v2_1_b2s_rd_cmd_fsm.v" \
    "$ref_dir/./../../../../zynq-memory-ordering.srcs/sources_1/bd/block_diagram/ipshared/xilinx.com/axi_protocol_converter_v2_1/hdl/verilog/axi_protocol_converter_v2_1_b2s_cmd_translator.v" \
    "$ref_dir/./../../../../zynq-memory-ordering.srcs/sources_1/bd/block_diagram/ipshared/xilinx.com/axi_protocol_converter_v2_1/hdl/verilog/axi_protocol_converter_v2_1_b2s_b_channel.v" \
    "$ref_dir/./../../../../zynq-memory-ordering.srcs/sources_1/bd/block_diagram/ipshared/xilinx.com/axi_protocol_converter_v2_1/hdl/verilog/axi_protocol_converter_v2_1_b2s_r_channel.v" \
    "$ref_dir/./../../../../zynq-memory-ordering.srcs/sources_1/bd/block_diagram/ipshared/xilinx.com/axi_protocol_converter_v2_1/hdl/verilog/axi_protocol_converter_v2_1_b2s_aw_channel.v" \
    "$ref_dir/./../../../../zynq-memory-ordering.srcs/sources_1/bd/block_diagram/ipshared/xilinx.com/axi_protocol_converter_v2_1/hdl/verilog/axi_protocol_converter_v2_1_b2s_ar_channel.v" \
    "$ref_dir/./../../../../zynq-memory-ordering.srcs/sources_1/bd/block_diagram/ipshared/xilinx.com/axi_protocol_converter_v2_1/hdl/verilog/axi_protocol_converter_v2_1_b2s.v" \
    "$ref_dir/./../../../../zynq-memory-ordering.srcs/sources_1/bd/block_diagram/ipshared/xilinx.com/axi_protocol_converter_v2_1/hdl/verilog/axi_protocol_converter_v2_1_axi_protocol_converter.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $opts_ver +v2k +incdir+"$ref_dir/../../../../zynq-memory-ordering.srcs/sources_1/bd/block_diagram/ipshared/xilinx.com/axi_infrastructure_v1_1/hdl/verilog" +incdir+"$ref_dir/../../../../zynq-memory-ordering.srcs/sources_1/bd/block_diagram/ipshared/xilinx.com/processing_system7_bfm_v2_0/hdl" +incdir+"$ref_dir/../../../bd/block_diagram/ip/block_diagram_processing_system7_0_0" +incdir+"$ref_dir/../../../bd/block_diagram/ipshared/xilinx.com/ila_v6_0/hdl/verilog" +incdir+"$ref_dir/../../../bd/block_diagram/ipshared/xilinx.com/ltlib_v1_0/hdl/verilog" +incdir+"$ref_dir/../../../bd/block_diagram/ipshared/xilinx.com/xsdbm_v1_1/hdl/verilog" +incdir+"$ref_dir/../../../bd/block_diagram/ipshared/xilinx.com/xsdbs_v1_0/hdl/verilog" +incdir+"$ref_dir/../../../../zynq-memory-ordering.srcs/sources_1/bd/block_diagram/ip/block_diagram_processing_system7_0_0" +incdir+"$ref_dir/../../../../zynq-memory-ordering.srcs/sources_1/bd/block_diagram/ipshared/user.org/hardware_accelerator_v1_0/drivers/hardware-accelerator_v1_0/src" +incdir+"$ref_dir/../../../../zynq-memory-ordering.srcs/sources_1/bd/block_diagram/ipshared/xilinx.com/axi4_metrics_counter_v1_0/drivers/axi3_metrics_counter_v1_0/src" +incdir+"$ref_dir/../../../../zynq-memory-ordering.srcs/sources_1/bd/block_diagram/ipshared/xilinx.com/ila_v6_0/hdl/verilog" +incdir+"$ref_dir/../../../../zynq-memory-ordering.srcs/sources_1/bd/block_diagram/ipshared/xilinx.com/ltlib_v1_0/hdl/verilog" +incdir+"$ref_dir/../../../../zynq-memory-ordering.srcs/sources_1/bd/block_diagram/ipshared/xilinx.com/xsdbm_v1_1/hdl/verilog" +incdir+"$ref_dir/../../../../zynq-memory-ordering.srcs/sources_1/bd/block_diagram/ipshared/xilinx.com/xsdbs_v1_0/hdl/verilog" +incdir+"$ref_dir/../../../ipstatic/axi_infrastructure_v1_1/hdl/verilog" +incdir+"$ref_dir/../../../ipstatic/processing_system7_bfm_v2_0/hdl" \
    "$ref_dir/./../../../bd/block_diagram/ip/block_diagram_auto_pc_0/sim/block_diagram_auto_pc_0.v" \
    "$ref_dir/./../../../bd/block_diagram/ip/block_diagram_auto_pc_1/sim/block_diagram_auto_pc_1.v" \
    "$ref_dir/./../../../bd/block_diagram/hdl/block_diagram.v" \
  2>&1 | tee -a vlogan.log


  vlogan -work xil_defaultlib $opts_ver +v2k \
    ./glbl.v \
  2>&1 | tee -a vlogan.log

}

# RUN_STEP: <elaborate>
elaborate()
{
  opts="-load "/opt/Xilinx/Vivado/2015.3/lib/lnx64.o/libxil_vcs.so:xilinx_register_systf" -full64 -debug_pp -t ps -licqueue -l elaborate.log"

  vcs $opts xil_defaultlib.block_diagram xil_defaultlib.glbl -o block_diagram_simv
}

# RUN_STEP: <simulate>
simulate()
{
  opts="-ucli -licqueue -l simulate.log"

  ./block_diagram_simv $opts -do simulate.do
}
# Script usage
usage()
{
  msg="Usage: block_diagram.sh [-help]\n\
Usage: block_diagram.sh [-lib_map_path]\n\
Usage: block_diagram.sh [-reset_run]\n\
Usage: block_diagram.sh [-noclean_files]\n\n\
[-help] -- Print help information for this script\n\n\
[-lib_map_path <path>] -- Compiled simulation library directory path. The simulation library is compiled\n\
using the compile_simlib tcl command. Please see 'compile_simlib -help' for more information.\n\n\
[-reset_run] -- Recreate simulator setup files and library mappings for a clean run. The generated files\n\
from the previous run will be removed. If you don't want to remove the simulator generated files, use the\n\
-noclean_files switch.\n\n\
[-noclean_files] -- Reset previous run, but do not remove simulator generated files from the previous run.\n\n"
  echo -e $msg
  exit 1
}


# Launch script
run $1 $2
