# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7z020clg484-1

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir /opt/Xilinx/Projects/zynq-memory-ordering/zynq-memory-ordering.cache/wt [current_project]
set_property parent.project_path /opt/Xilinx/Projects/zynq-memory-ordering/zynq-memory-ordering.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part em.avnet.com:zed:part0:1.3 [current_project]
set_property ip_repo_paths /opt/Xilinx/Projects/zynq-memory-ordering/ip_repo [current_project]
set_property vhdl_version vhdl_2k [current_fileset]
add_files /opt/Xilinx/Projects/zynq-memory-ordering/zynq-memory-ordering.srcs/sources_1/bd/block_diagram/block_diagram.bd
set_property used_in_implementation false [get_files -all /opt/Xilinx/Projects/zynq-memory-ordering/zynq-memory-ordering.srcs/sources_1/bd/block_diagram/ip/block_diagram_processing_system7_0_0/block_diagram_processing_system7_0_0.xdc]
set_property used_in_implementation false [get_files -all /opt/Xilinx/Projects/zynq-memory-ordering/zynq-memory-ordering.srcs/sources_1/bd/block_diagram/ip/block_diagram_proc_sys_reset_0_0/block_diagram_proc_sys_reset_0_0_board.xdc]
set_property used_in_implementation false [get_files -all /opt/Xilinx/Projects/zynq-memory-ordering/zynq-memory-ordering.srcs/sources_1/bd/block_diagram/ip/block_diagram_proc_sys_reset_0_0/block_diagram_proc_sys_reset_0_0.xdc]
set_property used_in_implementation false [get_files -all /opt/Xilinx/Projects/zynq-memory-ordering/zynq-memory-ordering.srcs/sources_1/bd/block_diagram/ip/block_diagram_proc_sys_reset_0_0/block_diagram_proc_sys_reset_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /opt/Xilinx/Projects/zynq-memory-ordering/zynq-memory-ordering.srcs/sources_1/bd/block_diagram/ip/block_diagram_xbar_0/block_diagram_xbar_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /opt/Xilinx/Projects/zynq-memory-ordering/zynq-memory-ordering.srcs/sources_1/bd/block_diagram/ip/block_diagram_ila_0_0/ila_v6_0/constraints/ila.xdc]
set_property used_in_implementation false [get_files -all /opt/Xilinx/Projects/zynq-memory-ordering/zynq-memory-ordering.srcs/sources_1/bd/block_diagram/ip/block_diagram_ila_0_0/block_diagram_ila_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /opt/Xilinx/Projects/zynq-memory-ordering/zynq-memory-ordering.srcs/sources_1/bd/block_diagram/ip/block_diagram_auto_pc_0/block_diagram_auto_pc_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /opt/Xilinx/Projects/zynq-memory-ordering/zynq-memory-ordering.srcs/sources_1/bd/block_diagram/ip/block_diagram_auto_pc_1/block_diagram_auto_pc_1_ooc.xdc]
set_property used_in_implementation false [get_files -all /opt/Xilinx/Projects/zynq-memory-ordering/zynq-memory-ordering.srcs/sources_1/bd/block_diagram/block_diagram_ooc.xdc]
set_property is_locked true [get_files /opt/Xilinx/Projects/zynq-memory-ordering/zynq-memory-ordering.srcs/sources_1/bd/block_diagram/block_diagram.bd]

read_verilog -library xil_defaultlib /opt/Xilinx/Projects/zynq-memory-ordering/zynq-memory-ordering.srcs/sources_1/bd/block_diagram/hdl/block_diagram_wrapper.v
read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
synth_design -top block_diagram_wrapper -part xc7z020clg484-1
write_checkpoint -noxdef block_diagram_wrapper.dcp
catch { report_utilization -file block_diagram_wrapper_utilization_synth.rpt -pb block_diagram_wrapper_utilization_synth.pb }
