# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/block_diagram/block_diagram.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==block_diagram || ORIG_REF_NAME==block_diagram}]

# IP: bd/block_diagram/ip/block_diagram_processing_system7_0_0/block_diagram_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==block_diagram_processing_system7_0_0 || ORIG_REF_NAME==block_diagram_processing_system7_0_0}]

# IP: bd/block_diagram/ip/block_diagram_proc_sys_reset_0_0/block_diagram_proc_sys_reset_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==block_diagram_proc_sys_reset_0_0 || ORIG_REF_NAME==block_diagram_proc_sys_reset_0_0}]

# IP: bd/block_diagram/ip/block_diagram_hardware_accelerator_0_0/block_diagram_hardware_accelerator_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==block_diagram_hardware_accelerator_0_0 || ORIG_REF_NAME==block_diagram_hardware_accelerator_0_0}]

# IP: bd/block_diagram/ip/block_diagram_axi_interconnect_0_0/block_diagram_axi_interconnect_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==block_diagram_axi_interconnect_0_0 || ORIG_REF_NAME==block_diagram_axi_interconnect_0_0}]

# IP: bd/block_diagram/ip/block_diagram_axi_interconnect_1_0/block_diagram_axi_interconnect_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==block_diagram_axi_interconnect_1_0 || ORIG_REF_NAME==block_diagram_axi_interconnect_1_0}]

# IP: bd/block_diagram/ip/block_diagram_xbar_0/block_diagram_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==block_diagram_xbar_0 || ORIG_REF_NAME==block_diagram_xbar_0}]

# IP: bd/block_diagram/ip/block_diagram_axi4_metrics_counter_0_0/block_diagram_axi4_metrics_counter_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==block_diagram_axi4_metrics_counter_0_0 || ORIG_REF_NAME==block_diagram_axi4_metrics_counter_0_0}]

# IP: bd/block_diagram/ip/block_diagram_xlslice_0_0/block_diagram_xlslice_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==block_diagram_xlslice_0_0 || ORIG_REF_NAME==block_diagram_xlslice_0_0}]

# IP: bd/block_diagram/ip/block_diagram_xlslice_0_1/block_diagram_xlslice_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==block_diagram_xlslice_0_1 || ORIG_REF_NAME==block_diagram_xlslice_0_1}]

# IP: bd/block_diagram/ip/block_diagram_util_reduced_logic_0_0/block_diagram_util_reduced_logic_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==block_diagram_util_reduced_logic_0_0 || ORIG_REF_NAME==block_diagram_util_reduced_logic_0_0}]

# IP: bd/block_diagram/ip/block_diagram_xlconcat_0_0/block_diagram_xlconcat_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==block_diagram_xlconcat_0_0 || ORIG_REF_NAME==block_diagram_xlconcat_0_0}]

# IP: bd/block_diagram/ip/block_diagram_xlslice_0_2/block_diagram_xlslice_0_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==block_diagram_xlslice_0_2 || ORIG_REF_NAME==block_diagram_xlslice_0_2}]

# IP: bd/block_diagram/ip/block_diagram_xlslice_0_3/block_diagram_xlslice_0_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==block_diagram_xlslice_0_3 || ORIG_REF_NAME==block_diagram_xlslice_0_3}]

# IP: bd/block_diagram/ip/block_diagram_util_vector_logic_0_0/block_diagram_util_vector_logic_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==block_diagram_util_vector_logic_0_0 || ORIG_REF_NAME==block_diagram_util_vector_logic_0_0}]

# IP: bd/block_diagram/ip/block_diagram_xlconcat_0_1/block_diagram_xlconcat_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==block_diagram_xlconcat_0_1 || ORIG_REF_NAME==block_diagram_xlconcat_0_1}]

# IP: bd/block_diagram/ip/block_diagram_util_vector_logic_1_0/block_diagram_util_vector_logic_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==block_diagram_util_vector_logic_1_0 || ORIG_REF_NAME==block_diagram_util_vector_logic_1_0}]

# IP: bd/block_diagram/ip/block_diagram_util_reduced_logic_0_1/block_diagram_util_reduced_logic_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==block_diagram_util_reduced_logic_0_1 || ORIG_REF_NAME==block_diagram_util_reduced_logic_0_1}]

# IP: bd/block_diagram/ip/block_diagram_xlconcat_1_1/block_diagram_xlconcat_1_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==block_diagram_xlconcat_1_1 || ORIG_REF_NAME==block_diagram_xlconcat_1_1}]

# IP: bd/block_diagram/ip/block_diagram_xlconcat_0_2/block_diagram_xlconcat_0_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==block_diagram_xlconcat_0_2 || ORIG_REF_NAME==block_diagram_xlconcat_0_2}]

# IP: bd/block_diagram/ip/block_diagram_ila_0_0/block_diagram_ila_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==block_diagram_ila_0_0 || ORIG_REF_NAME==block_diagram_ila_0_0}]

# IP: bd/block_diagram/ip/block_diagram_auto_pc_0/block_diagram_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==block_diagram_auto_pc_0 || ORIG_REF_NAME==block_diagram_auto_pc_0}]

# IP: bd/block_diagram/ip/block_diagram_auto_pc_1/block_diagram_auto_pc_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==block_diagram_auto_pc_1 || ORIG_REF_NAME==block_diagram_auto_pc_1}]

# XDC: bd/block_diagram/ip/block_diagram_processing_system7_0_0/block_diagram_processing_system7_0_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==block_diagram_processing_system7_0_0 || ORIG_REF_NAME==block_diagram_processing_system7_0_0}] {/inst }]/inst ]]

# XDC: bd/block_diagram/ip/block_diagram_proc_sys_reset_0_0/block_diagram_proc_sys_reset_0_0_board.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==block_diagram_proc_sys_reset_0_0 || ORIG_REF_NAME==block_diagram_proc_sys_reset_0_0}]

# XDC: bd/block_diagram/ip/block_diagram_proc_sys_reset_0_0/block_diagram_proc_sys_reset_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==block_diagram_proc_sys_reset_0_0 || ORIG_REF_NAME==block_diagram_proc_sys_reset_0_0}]

# XDC: bd/block_diagram/ip/block_diagram_proc_sys_reset_0_0/block_diagram_proc_sys_reset_0_0_ooc.xdc

# XDC: bd/block_diagram/ip/block_diagram_xbar_0/block_diagram_xbar_0_ooc.xdc

# XDC: bd/block_diagram/ip/block_diagram_ila_0_0/ila_v6_0/constraints/ila.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==block_diagram_ila_0_0 || ORIG_REF_NAME==block_diagram_ila_0_0}]

# XDC: bd/block_diagram/ip/block_diagram_ila_0_0/block_diagram_ila_0_0_ooc.xdc

# XDC: bd/block_diagram/ip/block_diagram_auto_pc_0/block_diagram_auto_pc_0_ooc.xdc

# XDC: bd/block_diagram/ip/block_diagram_auto_pc_1/block_diagram_auto_pc_1_ooc.xdc

# XDC: bd/block_diagram/block_diagram_ooc.xdc
